import { createServerClient } from '@/lib/supabaseServer'
import { notFound } from 'next/navigation'
import Link from 'next/link'

export default async function SharedReportPage({
  params,
}: {
  params: Promise<{ token: string }>
}) {
  const { token } = await params
  const supabase = await createServerClient()

  const { data: report } = await supabase
    .from('reports')
    .select('*')
    .eq('share_token', token)
    .eq('is_public', true)
    .single()

  if (!report) notFound()

  const { data: findings } = await supabase
    .from('findings')
    .select('*')
    .eq('report_id', report.id)
    .order('severity', { ascending: false })

  const scoreColor = (score: number) =>
    score >= 80 ? 'text-emerald-400' : score >= 60 ? 'text-yellow-400' : 'text-red-400'

  return (
    <div className="min-h-screen bg-zinc-950 text-white">
      {/* Powered-by banner */}
      <div className="bg-gradient-to-r from-purple-600 to-indigo-600 text-white text-center py-2.5 text-xs font-bold">
        This audit was generated by Auditor AI —{' '}
        <Link href="/" className="underline hover:no-underline">Get your free audit</Link>
      </div>

      <main className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
        {/* Header */}
        <div className="space-y-4">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-purple-500/10 border border-purple-500/20 text-purple-400 text-xs font-bold uppercase tracking-wider">
            <span className="w-1.5 h-1.5 rounded-full bg-purple-500"></span>
            Shared Report
          </div>
          <h1 className="text-3xl md:text-5xl font-black tracking-tight">
            {report.url.replace('https://', '').replace('http://', '')}
          </h1>
          <p className="text-zinc-500 text-sm font-medium">
            Audited on {new Date(report.created_at).toLocaleDateString(undefined, { dateStyle: 'long' })}
          </p>
        </div>

        {/* Scores */}
        <div className="grid grid-cols-2 md:grid-cols-5 gap-4">
          {[
            { label: 'Overall', score: report.overall_score },
            { label: 'SEO', score: report.seo_score },
            { label: 'UX', score: report.ux_score },
            { label: 'Copy', score: report.copywriting_score },
            { label: 'Trust', score: report.trust_signals_score },
          ].map((item) => (
            <div key={item.label} className="bg-zinc-900 rounded-2xl p-6 border border-zinc-800 text-center">
              <div className={`text-3xl font-black ${scoreColor(item.score)}`}>{item.score}</div>
              <div className="text-[10px] font-bold text-zinc-500 uppercase tracking-widest mt-1">{item.label}</div>
            </div>
          ))}
        </div>

        {/* Screenshot */}
        {report.screenshot_url && (
          <div className="rounded-2xl overflow-hidden border border-zinc-800">
            {/* eslint-disable-next-line @next/next/no-img-element */}
            <img src={report.screenshot_url} alt="Page screenshot" className="w-full" />
          </div>
        )}

        {/* Findings */}
        {findings && findings.length > 0 && (
          <div className="space-y-4">
            <h2 className="text-2xl font-black">Findings</h2>
            <div className="space-y-3">
              {findings.map((f: any, i: number) => {
                const severityColors: Record<string, string> = {
                  high: 'border-red-500/30 bg-red-500/5',
                  medium: 'border-amber-500/30 bg-amber-500/5',
                  low: 'border-blue-500/30 bg-blue-500/5',
                }
                return (
                  <div key={i} className={`p-5 rounded-xl border ${severityColors[f.severity] || 'border-zinc-800'}`}>
                    <div className="flex items-center gap-2 mb-2">
                      <span className="text-[10px] font-black uppercase tracking-widest text-zinc-500 px-2 py-0.5 bg-zinc-900 rounded">{f.issue_type}</span>
                      <span className="text-[10px] font-black uppercase tracking-widest text-zinc-500">{f.severity}</span>
                    </div>
                    <p className="text-sm text-zinc-300 font-medium">{f.suggestion}</p>
                  </div>
                )
              })}
            </div>
          </div>
        )}

        {/* Copy Rewrites */}
        {report.copy_rewrites?.length > 0 && (
          <div className="space-y-4">
            <h2 className="text-2xl font-black">Suggested Copy Rewrites</h2>
            <div className="space-y-3">
              {report.copy_rewrites.map((r: any, i: number) => (
                <div key={i} className="rounded-xl border border-zinc-800 overflow-hidden">
                  <div className="px-4 py-2 bg-zinc-900 text-xs font-bold text-zinc-400 uppercase tracking-widest">{r.section}</div>
                  <div className="grid grid-cols-1 sm:grid-cols-2 divide-y sm:divide-y-0 sm:divide-x divide-zinc-800">
                    <div className="p-4">
                      <div className="text-[10px] font-black text-red-400 uppercase mb-1">Before</div>
                      <p className="text-sm text-zinc-400">{r.original}</p>
                    </div>
                    <div className="p-4 bg-emerald-500/5">
                      <div className="text-[10px] font-black text-emerald-400 uppercase mb-1">After</div>
                      <p className="text-sm text-white font-medium">{r.improved}</p>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}

        {/* CTA */}
        <div className="text-center py-12">
          <Link
            href="/audit"
            className="inline-flex px-10 py-5 bg-gradient-to-r from-purple-600 to-indigo-600 text-white rounded-2xl font-black text-lg transition-all hover:scale-105 active:scale-95 shadow-xl shadow-purple-900/30"
          >
            Get Your Own Free Audit →
          </Link>
        </div>
      </main>
    </div>
  )
}
