import React from 'react'
import { Document, Page, Text, View, StyleSheet, Font } from '@react-pdf/renderer'

// Register a standard font (Helvetica is built-in)
Font.register({ family: 'Helvetica', fonts: [{ src: 'https://fonts.gstatic.com/s/helvetica/v1/Helvetica.ttf' }] })

const styles = StyleSheet.create({
  page: { padding: 30, fontFamily: 'Helvetica' },
  header: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 20, borderBottom: 1, borderColor: '#eee', paddingBottom: 10 },
  title: { fontSize: 24, fontWeight: 'bold', color: '#6d28d9' }, // Purple brand color
  subtitle: { fontSize: 12, color: '#666' },
  section: { marginBottom: 20 },
  sectionTitle: { fontSize: 16, fontWeight: 'bold', marginBottom: 10, color: '#333' },
  scoreRow: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 5 },
  scoreLabel: { fontSize: 12, width: 100 },
  scoreValue: { fontSize: 12, fontWeight: 'bold' },
  progressBarBg: { height: 8, backgroundColor: '#eee', borderRadius: 4, overflow: 'hidden', width: 200 },
  progressBarFill: { height: 8, backgroundColor: '#6d28d9' },
  findingItem: { marginBottom: 10, paddingLeft: 10, borderLeftWidth: 3, borderLeftColor: '#ccc' },
  findingSeverityHigh: { borderLeftColor: '#ef4444' }, // Red
  findingSeverityMedium: { borderLeftColor: '#f59e0b' }, // Yellow
  findingSeverityLow: { borderLeftColor: '#3b82f6' }, // Blue
  findingTitle: { fontSize: 12, fontWeight: 'bold' },
  findingText: { fontSize: 10, color: '#555', marginTop: 2 },
  footer: { position: 'absolute', bottom: 30, left: 30, right: 30, textAlign: 'center', fontSize: 10, color: '#999' },
})

interface Finding {
  category: string
  severity: 'low' | 'medium' | 'high'
  issue: string
  suggestion: string
}

interface ReportData {
  url: string
  overall_score: number
  seo_score: number
  ux_score: number
  copywriting_score: number
  trust_signals_score: number
  findings: Finding[]
  created_at: string
}

export const AuditReportPDF = ({ data }: { data: ReportData }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      {/* Header */}
      <View style={styles.header}>
        <View>
          <Text style={styles.title}>Landing Page Audit</Text>
          <Text style={styles.subtitle}>Generated by AI Landing Page Auditor</Text>
        </View>
        <View style={{ textAlign: 'right' }}>
          <Text style={styles.subtitle}>{new Date(data.created_at).toLocaleDateString()}</Text>
          <Text style={styles.subtitle}>{data.url}</Text>
        </View>
      </View>

      {/* Scores Section */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Performance Scores</Text>
        
        <ScoreBar label="Overall" score={data.overall_score} />
        <ScoreBar label="SEO" score={data.seo_score} />
        <ScoreBar label="UX/UI" score={data.ux_score} />
        <ScoreBar label="Copywriting" score={data.copywriting_score} />
        <ScoreBar label="Trust Signals" score={data.trust_signals_score} />
      </View>

      {/* Findings Section */}
      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Key Issues & Recommendations</Text>
        {data.findings.slice(0, 10).map((finding, index) => (
          <View 
            key={index} 
            style={[
              styles.findingItem, 
              finding.severity === 'high' ? styles.findingSeverityHigh : 
              finding.severity === 'medium' ? styles.findingSeverityMedium : 
              styles.findingSeverityLow
            ]}
          >
            <Text style={styles.findingTitle}>
              [{finding.severity.toUpperCase()}] {finding.category}: {finding.issue}
            </Text>
            <Text style={styles.findingText}>💡 {finding.suggestion}</Text>
          </View>
        ))}
      </View>

      {/* Footer */}
      <Text style={styles.footer}>
        This report was generated automatically by AI Landing Page Auditor. For questions, contact support.
      </Text>
    </Page>
  </Document>
)

// Helper Component for Score Bars
const ScoreBar = ({ label, score }: { label: string; score: number }) => (
  <View style={styles.scoreRow}>
    <Text style={styles.scoreLabel}>{label}</Text>
    <View style={{ flex: 1, marginRight: 10 }}>
      <View style={styles.progressBarBg}>
        <View style={{ ...styles.progressBarFill, width: `${score}%` }} />
      </View>
    </View>
    <Text style={styles.scoreValue}>{score}/100</Text>
  </View>
)